fedora31: fix mariadb dependency
Error: Transaction test error:
  file /usr/include/mysql/mariadb_rpl.h conflicts between attempted installs of mariadb-devel-3:10.3.22-1.fc31.x86_64 and mariadb-connector-c-devel-3.1.9-5.fc31.x86_64

when building mariadb client applications, mariadb-connector-c-devel should be used.