omd: fix help text containing percentage signs
Fixes the issue on with python 3.14

    cmd: '/usr/bin/omd create  testsite' failed

    Traceback (most recent call last):
      File "/usr/lib/python3.14/argparse.py", line 1759, in _check_help
        formatter._expand_help(action)
        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
      File "/usr/lib/python3.14/argparse.py", line 687, in _expand_help
        return help_string % params
               ~~~~~~~~~~~~^~~~~~~~
    TypeError: %o format: an integer is required, not dict

    The above exception was the direct cause of the following exception

    Traceback (most recent call last):
      File "/usr/bin/omd", line 40, in <module>
        omd.run(OMD_VERSION)
        ~~~~~~~^^^^^^^^^^^^^
      File "/omd/versions/5.61.20260413-labs-edition/lib/python/omd/omd.py", line 5460, in run
        argparser.add_argument(spec[0], spec[1], **spec[2])
        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.14/argparse.py", line 1573, in add_argument
        self._check_help(action)
        ~~~~~~~~~~~~~~~~^^^^^^^^
      File "/usr/lib/python3.14/argparse.py", line 1761, in _check_help
        raise ValueError('badly formed help string') from exc
    ValueError: badly formed help string
    started here at t/TestUtils.pm line 196.